import { sql } from 'drizzle-orm';
import { boolean, integer, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  googleId: text('google_id').notNull().unique(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  avatarUrl: text('avatar_url'),
  status: text('status', { enum: ['active', 'suspended'] }).notNull().default('active'),
  city: text('city'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const sessions = pgTable('sessions', {
  token: uuid('token').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  deviceModel: text('device_model'),
  osVersion: text('os_version'),
  appVersion: text('app_version'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  // The DB-level default (used as the migration backfill for existing rows,
  // and as a safety net for any insert that doesn't set it explicitly) mirrors
  // SESSION_TTL_MS in users-store.ts, which is what actually sets this on
  // every new session going forward.
  expiresAt: timestamp('expires_at').notNull().default(sql`now() + interval '90 days'`),
});

export const conversations = pgTable('conversations', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }),
  title: text('title').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const messages = pgTable('messages', {
  id: uuid('id').primaryKey().defaultRandom(),
  conversationId: uuid('conversation_id')
    .notNull()
    .references(() => conversations.id, { onDelete: 'cascade' }),
  from: text('from', { enum: ['me', 'bot'] }).notNull(),
  text: text('text').notNull(),
  attachmentName: text('attachment_name'),
  reaction: text('reaction', { enum: ['like', 'dislike'] }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const prompts = pgTable('prompts', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  author: text('author').notNull().default(''),
  category: text('category').notNull().default(''),
  color: text('color').notNull().default('#F3A7C7'),
  emoji: text('emoji'),
  featured: boolean('featured').notNull().default(false),
  // 'auto' rows are generated by generateAutoPrompts() (see auto-prompts.ts)
  // and replaced wholesale on each run - 'admin' rows are hand-curated via
  // the dashboard and never touched by that job.
  source: text('source', { enum: ['admin', 'auto'] }).notNull().default('admin'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const feedback = pgTable('feedback', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  message: text('message').notNull(),
  appVersion: text('app_version'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

// Tracks when the admin last opened each notified section ('users' |
// 'feedback'), so the sidebar badge can show a count of items created since
// then. One row per key - there's a single shared admin login (HTTP Basic,
// any username), not per-admin accounts, so this doesn't need a user column.
export const adminNotificationState = pgTable('admin_notification_state', {
  key: text('key').primaryKey(),
  lastViewedAt: timestamp('last_viewed_at').notNull().defaultNow(),
});

export const userMemories = pgTable('user_memories', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  content: text('content').notNull(),
  sourceConversationId: uuid('source_conversation_id').references(() => conversations.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const appReleases = pgTable('app_releases', {
  id: uuid('id').primaryKey().defaultRandom(),
  version: text('version').notNull(),
  versionCode: integer('version_code').notNull(),
  apkUrl: text('apk_url').notNull(),
  mandatory: boolean('mandatory').notNull().default(false),
  notes: text('notes'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const emailTemplates = pgTable('email_templates', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  subject: text('subject').notNull(),
  // Plain text with a "{{name}}" placeholder, not HTML - kept simple like the
  // rest of the dashboard's hand-rolled tools. Wrapped in the branded HTML
  // shell at send time (see email.ts).
  body: text('body').notNull(),
  // Which of the hand-built HTML layouts in email.ts wraps this template's
  // text - 'announcement' (sober card), 'promo' (bold banner), 'newsletter'
  // (dark masthead + footer). See EMAIL_DESIGNS in email.ts.
  design: text('design', { enum: ['announcement', 'promo', 'newsletter'] }).notNull().default('announcement'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

// One row per "send" action from the dashboard - a log, not a queue (sends
// happen synchronously in the request). Lets the admin see what went out and
// to how many people without re-reading their email client.
export const emailCampaigns = pgTable('email_campaigns', {
  id: uuid('id').primaryKey().defaultRandom(),
  subject: text('subject').notNull(),
  body: text('body').notNull(),
  design: text('design', { enum: ['announcement', 'promo', 'newsletter'] }).notNull().default('announcement'),
  recipientCount: integer('recipient_count').notNull(),
  failureCount: integer('failure_count').notNull().default(0),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

// The Communication module's core content type. `content` uses the same
// lightweight markdown (**bold**, *italic*, paragraphs) as chat messages -
// the app renders it with the same <MessageContent> component, so there's
// no second parser to maintain and no rich-text-editor dependency to add.
export const announcements = pgTable('announcements', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  content: text('content').notNull(),
  imageUrl: text('image_url'),
  type: text('type', { enum: ['update', 'info', 'tip', 'prompt', 'promo', 'poll', 'security'] })
    .notNull()
    .default('info'),
  // 'scheduled' and 'published' are both live states, just before/after
  // publishAt - announcements-scheduler.ts flips scheduled->published and
  // published->expired on a timer so the admin never has to do it by hand.
  status: text('status', { enum: ['draft', 'scheduled', 'published', 'expired', 'archived'] })
    .notNull()
    .default('draft'),
  target: text('target', { enum: ['all', 'new', 'active', 'inactive'] }).notNull().default('all'),
  pinned: boolean('pinned').notNull().default(false),
  sendEmail: boolean('send_email').notNull().default(false),
  emailSentAt: timestamp('email_sent_at'),
  publishAt: timestamp('publish_at').notNull().defaultNow(),
  expiresAt: timestamp('expires_at'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});
